<script lang="ts">
	import EmailHtmlFrame from '$lib/components/mail/EmailHtmlFrame.svelte';
	import { renderMessageBody } from '$lib/email/html';
	import { settings } from '$lib/stores/settings.svelte';
	import { theme } from '$lib/stores/theme.svelte';

	interface Props {
		bodyHtml?: string;
		bodyText: string;
		allowExternal: boolean;
	}

	let { bodyHtml, bodyText, allowExternal }: Props = $props();

	const darkMode = $derived(theme.resolved === 'dark');

	const rendered = $derived(
		renderMessageBody({
			bodyHtml,
			bodyText,
			allowExternal,
			darkMode,
			preferPlainText: settings.preferPlainText,
			cleanView: settings.readerCleanView
		})
	);
</script>

{#if rendered.isHtml}
	<!-- Untrusted email HTML renders in a sandboxed iframe for CSS + script isolation. -->
	<div class="w-full">
		<EmailHtmlFrame html={rendered.html} {darkMode} lightSurface={rendered.lightSurface} />
	</div>
{:else}
	<!-- Plain-text bodies are generated by us (linkified, escaped) — safe to inline. -->
	<div class="z-email-body z-email-body--plain w-full whitespace-pre-wrap">
		{@html rendered.html}
	</div>
{/if}
