/** Auto-generated by scripts/generate-settings-index.mjs — do not edit manually. */

export const SETTINGS_PAGE_HIDDEN_COUNTS: Record<string, number> = {
	"/settings/appearance": 12,
	"/settings/inbox": 14,
	"/settings/reading": 28,
	"/settings/compose": 8,
	"/settings/workspace": 26,
	"/settings/calendar": 15,
	"/settings/contacts": 15,
	"/settings/data": 0,
	"/settings/account": 1,
	"/settings/mail": 5
};

export function hiddenSettingsCountForPage(pathname: string): number {
	return SETTINGS_PAGE_HIDDEN_COUNTS[pathname] ?? 0;
}
