/** Auto-generated by scripts/generate-settings-index.mjs — do not edit manually. */

export const SETTINGS_PAGE_HIDDEN_COUNTS: Record<string, number> = {
	"/settings/appearance": 3,
	"/settings/layout": 5,
	"/settings/sidebar": 5,
	"/settings/inbox": 9,
	"/settings/reading": 19,
	"/settings/compose": 8,
	"/settings/calendar": 15,
	"/settings/contacts": 15,
	"/settings/data": 0,
	"/settings/account": 0,
	"/settings/mail": 1
};

export function hiddenSettingsCountForPage(pathname: string): number {
	return SETTINGS_PAGE_HIDDEN_COUNTS[pathname] ?? 0;
}
