captainVersion: 4
caproverOneClickApp:
  variables:
    - id: $$cap_app_name
      label: App Name
      defaultValue: zaur
      description: Name of your Zaur app
    - id: $$cap_rethinkdb_host
      label: RethinkDB Host
      defaultValue: rethink.zaur.app
      description: RethinkDB hostname or IP address
    - id: $$cap_rethinkdb_port
      label: RethinkDB Port
      defaultValue: 28015
      description: RethinkDB port
    - id: $$cap_rethinkdb_db
      label: RethinkDB Database
      defaultValue: zaur_news
      description: RethinkDB database name
  instructions:
    start: >-
      Zaur Dashboard deployment configuration.
      This definition will help you deploy the Zaur dashboard app with RethinkDB connection.
    end: >-
      Your Zaur app has been deployed successfully! 
      You can access it using your CapRover domain.
  displayName: Zaur Dashboard
  description: The Zaur dashboard and news aggregator
  documentation: https://github.com/yourusername/zaur
services:
  $$cap_app_name:
    image: $$cap_app_name:latest
    restart: always
    caproverExtra:
      containerHttpPort: '3000'
    environment:
      NODE_ENV: production
      PORT: 3000
      HOST: 0.0.0.0
      RETHINKDB_HOST: $$cap_rethinkdb_host
      RETHINKDB_PORT: $$cap_rethinkdb_port
      RETHINKDB_DB: $$cap_rethinkdb_db 