/** Legacy density / layout keys removed after Simple mode — purged on init and excluded from sync. */
export const OBSOLETE_SETTING_KEYS = new Set([
	'zaur:auto-load-more',
	'zaur:search-scope',
	'zaur:show-reader-list-rail',
	'zaur:focus-reading-default',
	'zaur:mark-as-read-delay',
	'zaur:reader-width',
	'zaur:show-avatars',
	'zaur:show-quick-reply',
	'zaur:auto-archive-on-reply',
	'zaur:return-to-inbox-after-send',
	'zaur:hide-external-content-banner',
	'zaur:hide-reader-recipients',
	'zaur:tool-icons-only',
	'zaur:hide-empty-reader-prompts',
	'zaur:hide-empty-reader-description',
	'zaur:hide-empty-reader-actions',
	'zaur:hide-empty-reader-icon',
	'zaur:hide-thread-summary',
	'zaur:show-bulk-select',
	'zaur:hide-header-search',
	'zaur:hide-offline-indicator',
	'zaur:show-reader-contact-actions',
	'zaur:show-search-contact-suggestions',
	'zaur:compact-header-actions',
	'zaur:hide-app-title',
	'zaur:compact-user-menu',
	'zaur:hide-list-empty-hints',
	'zaur:hide-list-empty-actions',
	'zaur:hide-selection-hints',
	'zaur:hide-reader-timestamps',
	'zaur:hide-collapsed-thread-previews',
	'zaur:hide-settings-nav-hints',
	'zaur:hide-settings-panel-descriptions',
	'zaur:compact-attachments',
	'zaur:hide-reader-sender-email',
	'zaur:hide-compose-from-line',
	'zaur:hide-compose-field-labels',
	'zaur:hide-outbox-unless-failed',
	'zaur:hide-move-menu-labels',
	'zaur:icon-only-compose-attach',
	'zaur:compact-reader-header',
	'zaur:compact-reader-body',
	'zaur:hide-connecting-screen',
	'zaur:compact-tool-switcher',
	'zaur:hide-search-dropdown-headers',
	'zaur:hide-pane-borders',
	'zaur:hide-list-row-dividers',
	'zaur:hide-reader-pane-borders',
	'zaur:hide-search-list-prefix',
	'zaur:compact-mobile-search',
	'zaur:hide-account-field-hints',
	'zaur:compact-quick-reply',
	'zaur:icon-only-compose-discard',
	'zaur:compact-toasts',
	'zaur:hide-toast-icons',
	'zaur:compact-load-more',
	'zaur:compact-user-menu-dropdown',
	'zaur:compact-outbox-menu',
	'zaur:compact-settings-rows',
	'zaur:compact-settings-layout',
	'zaur:compact-settings-panel',
	'zaur:compact-move-menu',
	'zaur:compact-search-dropdown',
	'zaur:compact-compose-suggestions',
	'zaur:compact-offline-indicator',
	'zaur:compact-app-header',
	'zaur:compact-empty-reader',
	'zaur:compact-settings-nav',
	'zaur:settings-detail-level',
	'zaur:hide-settings-back-link',
	'zaur:hide-settings-page-title',
	'zaur:hide-reader-status-back-button',
	'zaur:hide-reader-status-message',
	'zaur:compact-external-content-banner',
	'zaur:compact-contacts-page',
	'zaur:compact-contacts-list',
	'zaur:hide-contact-message-counts',
	'zaur:compact-list-empty-state',
	'zaur:compact-list-header',
	'zaur:compact-reader-toolbar',
	'zaur:compact-reader-avatars',
	'zaur:compact-collapsed-threads',
	'zaur:compact-reader-status',
	'zaur:compact-list-error-state',
	'zaur:hide-list-error-retry',
	'zaur:hide-contact-group-letters',
	'zaur:compact-contacts-add-form',
	'zaur:hide-contacts-page-subtitle',
	'zaur:compact-contacts-search',
	'zaur:compact-contacts-empty-state',
	'zaur:hide-contacts-header-settings',
	'zaur:hide-contacts-compose-button',
	'zaur:hide-contacts-empty-hints',
	'zaur:hide-contacts-empty-actions',
	'zaur:hide-contacts-hover-actions',
	'zaur:hide-contacts-row-mail-icon',
	'zaur:hide-contacts-email-line',
	'zaur:compact-calendar-grid',
	'zaur:compact-calendar-header',
	'zaur:compact-calendar-sidebar',
	'zaur:hide-calendar-more-events-label',
	'zaur:hide-calendar-sidebar-header',
	'zaur:hide-calendar-sidebar-settings',
	'zaur:hide-calendar-new-event-button',
	'zaur:icon-only-calendar-new-event',
	'zaur:compact-calendar-event-panel',
	'zaur:hide-calendar-empty-event-panel',
	'zaur:compact-calendar-empty-event-panel',
	'zaur:compact-calendar-compose',
	'zaur:hide-calendar-compose-field-labels',
	'zaur:hide-calendar-pane-borders',
	'zaur:compact-reader-inline-error',
	'zaur:minimal-reader-toolbar',
	'zaur:enable-undo-send',
	'zaur:warn-external-senders',
	'zaur:mail-view-mode',
	'zaur:traditional-mailbox-view',
	'zaur:focus-layout-mode',
	'zaur:accent-color'
]);

export function isObsoleteSettingKey(key: string): boolean {
	if (OBSOLETE_SETTING_KEYS.has(key)) return true;
	if (key.startsWith('zaur:compact-')) return true;
	if (key.startsWith('zaur:icon-only-')) return true;
	if (key.startsWith('zaur:minimal-')) return true;
	return false;
}

export function purgeObsoleteSettings(): void {
	if (typeof localStorage === 'undefined') return;
	const keys: string[] = [];
	for (let i = 0; i < localStorage.length; i++) {
		const key = localStorage.key(i);
		if (key && isObsoleteSettingKey(key)) keys.push(key);
	}
	for (const key of keys) localStorage.removeItem(key);
}
