/** Auto-generated by scripts/generate-settings-index.mjs — do not edit manually. */

export const SETTINGS_PAGE_HIDDEN_COUNTS: Record<string, number> = {
	"/settings/appearance": 0,
	"/settings/layout": 2,
	"/settings/inbox": 0,
	"/settings/reading": 1,
	"/settings/compose": 1,
	"/settings/calendar": 0,
	"/settings/data": 0,
	"/settings/account": 0,
	"/settings/mail": 1
};

export function hiddenSettingsCountForPage(pathname: string): number {
	return SETTINGS_PAGE_HIDDEN_COUNTS[pathname] ?? 0;
}
