<script lang="ts">
	import { frameSvg, type FrameId } from '@zaur/sprite';

	interface Props {
		/** Unseen messages in the active mailbox — drives look_up vs happy. */
		unread: number;
		/** Tooltip text; the mark also announces it to screen readers. */
		label?: string;
		/** Rendered width in px (height follows the 20:18 sprite grid). */
		size?: number;
	}

	let { unread, label, size = 28 }: Props = $props();

	const SLEEP_AFTER_MS = 5 * 60_000;
	const BLINK_MS = 180;
	const CHEER_MS = 2500;

	let offline = $state(false);
	let asleep = $state(false);
	let blinking = $state(false);
	let cheering = $state(false);

	// Sad beats everything (nothing else is true while the network is gone);
	// blink only interrupts the two resting faces.
	const frame = $derived<FrameId>(
		offline
			? 'sad'
			: cheering
				? 'cheer'
				: asleep
					? 'sleep'
					: blinking
						? 'blink'
						: unread > 0
							? 'look_up'
							: 'happy'
	);

	// scale 2 keeps the pixel grid crisp; CSS scales the box down to `size`.
	const svg = $derived(frameSvg(frame, { scale: 2, color: 'currentColor' }));

	const title = $derived(
		label ?? (unread > 0 ? `${unread} unseen` : 'Nothing unseen')
	);

	$effect(() => {
		const sync = () => (offline = !navigator.onLine);
		sync();
		addEventListener('online', sync);
		addEventListener('offline', sync);
		return () => {
			removeEventListener('online', sync);
			removeEventListener('offline', sync);
		};
	});

	// Reaching inbox zero is worth a cheer; arriving already at zero is not.
	// Deliberately a plain `let`: as $state it would be a dependency of the very
	// effect that writes it, and the re-run's cleanup would cancel the timer.
	let previousUnread: number | null = null;
	$effect(() => {
		const now = unread;
		const before = previousUnread;
		previousUnread = now;
		if (before === null || before === 0 || now !== 0) return;
		cheering = true;
		const timer = setTimeout(() => (cheering = false), CHEER_MS);
		// Unread arriving mid-cheer ends it — look_up is the truer face then.
		return () => {
			clearTimeout(timer);
			cheering = false;
		};
	});

	// Dozes off after a spell with no input, wakes on the next one.
	$effect(() => {
		let timer: ReturnType<typeof setTimeout>;
		const wake = () => {
			asleep = false;
			clearTimeout(timer);
			timer = setTimeout(() => (asleep = true), SLEEP_AFTER_MS);
		};
		wake();
		addEventListener('pointerdown', wake, { passive: true });
		addEventListener('keydown', wake, { passive: true });
		return () => {
			clearTimeout(timer);
			removeEventListener('pointerdown', wake);
			removeEventListener('keydown', wake);
		};
	});

	$effect(() => {
		if (matchMedia('(prefers-reduced-motion: reduce)').matches) return;
		let alive = true;
		let timer: ReturnType<typeof setTimeout>;
		const wait = (ms: number) =>
			new Promise<void>((resolve) => {
				timer = setTimeout(resolve, ms);
			});
		void (async () => {
			await wait(2000 + Math.random() * 3000);
			while (alive) {
				blinking = true;
				await wait(BLINK_MS);
				blinking = false;
				// A double blink now and then keeps it from looking metronomic.
				if (Math.random() < 0.3) {
					await wait(120);
					blinking = true;
					await wait(BLINK_MS);
					blinking = false;
				}
				await wait(2500 + Math.random() * 4500);
			}
		})();
		return () => {
			alive = false;
			clearTimeout(timer);
			blinking = false;
		};
	});
</script>

<!--
	The Zaur pixel mark stands in for the usual window traffic lights: it is the
	brand, and unlike three inert dots it says something — it looks up while
	unseen mail is waiting, cheers on reaching zero, sulks when the network
	drops, and dozes off when the app is left alone.
-->
<span
	role="img"
	aria-label="Zaur — {title}"
	{title}
	class="block shrink-0 text-slate-700 [&>svg]:h-auto [&>svg]:w-full"
	style:width="{size}px"
>
	<!-- eslint-disable-next-line svelte/no-at-html-tags -- generated by @zaur/sprite, no user input -->
	{@html svg}
</span>
