// Auto-generated by svelte-realtime - do not edit
// Provides client-side types for $live/ imports

declare module '$live/session-presence' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export type ErrorCode = 'UNAUTHORIZED';
  export const activeSessions: StreamStore<any | undefined | { error: RpcError }> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const empty: Readable<undefined>;
}
